### ISSUE TITLE
Documentation: Fix a broken link to the home page of the Cordova plugin in the README file

### ISSUE THREAD

**Issue by ilankri** [Thibaut-Gudin/ocaml-cordova-plugin-safariviewcontroller#2]
The link in question is in [this section](https://github.com/besport/ocaml-cordova-plugin-safariviewcontroller/blob/master/README.md#ocaml-cordova-plugin-safariviewcontroller).

**Comment by Thibaut-Gudin** [comment]
It will be fixed with this PR: https://github.com/besport/ocaml-cordova-plugin-safariviewcontroller/pull/3
